plugins {
    id "com.android.application"
}

android {
    namespace "com.quizmate.android"
    compileSdk 35
    buildToolsVersion "35.0.0"

    defaultConfig {
        applicationId "com.quizmate.android"
        minSdk 23
        targetSdk 34
        versionCode 20260731
        versionName "2026.07.31"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
